
name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: sam908qwe
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push the snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
